'use client';
import type { Account, PlatformKind, Snapshot, Post } from '@/lib/supabase/types';
import { PLATFORM_META } from '@/lib/platforms';
import { PlatformIcon } from '../dashboard/PlatformIcon';
import { formatNum } from '@/lib/utils';

const PLATFORM_ORDER: PlatformKind[] = [
  'instagram',
  'tiktok',
  'linkedin',
  'x',
  'youtube',
  'spotify',
  'captivate'
];

export function RecapPages({
  template,
  accounts,
  snapshotsByAccount,
  period
}: {
  template: string;
  accounts: Account[];
  snapshotsByAccount: Record<string, Array<Snapshot & { posts: Post[] }>>;
  period: string;
}) {
  const targetAccts =
    template === 'km-full'
      ? accounts.filter((a) => a.tag === 'KM')
      : template === 'tmmp-full'
      ? accounts.filter((a) => a.tag === 'TMMP')
      : accounts;

  const pages: React.ReactNode[] = [];

  // Cover
  pages.push(
    <CoverPage
      key="cover"
      title={
        template === 'km-full'
          ? 'KM'
          : template === 'tmmp-full'
          ? 'TMMP'
          : 'KM + TMMP'
      }
      period={period}
      accounts={targetAccts.map((a) => ({
        label: a.label,
        followers: (snapshotsByAccount[a.id] || []).reduce(
          (s, sn) => s + (sn.followers || 0),
          0
        ),
        growth: (snapshotsByAccount[a.id] || []).reduce(
          (s, sn) => s + (sn.growth || 0),
          0
        )
      }))}
    />
  );

  for (const a of targetAccts) {
    const snaps = snapshotsByAccount[a.id] || [];
    for (const platform of PLATFORM_ORDER) {
      const snap = snaps.find((s) => s.platform === platform);
      if (!snap || (!snap.followers && (!snap.posts || snap.posts.length === 0))) continue;
      pages.push(
        <PlatformRecapPage
          key={`${a.id}-${platform}`}
          account={a}
          snapshot={snap}
          period={period}
        />
      );
    }
  }

  return <>{pages}</>;
}

function CoverPage({
  title,
  period,
  accounts
}: {
  title: string;
  period: string;
  accounts: Array<{ label: string; followers: number; growth: number }>;
}) {
  return (
    <div
      className="recap-page relative overflow-hidden rounded-[14px] bg-[#0D1230] text-white"
      style={{ width: 864, height: 1152, boxShadow: '0 30px 80px rgba(0,0,0,.6)' }}
    >
      <div
        className="absolute inset-0"
        style={{
          background:
            'linear-gradient(160deg,#0D1230 0%,#141A45 60%,#7C3AED 130%)'
        }}
      />
      <div
        className="absolute -right-[20%] -top-[30%] h-[80%] w-[80%] rounded-full opacity-50 blur-[80px]"
        style={{ background: 'radial-gradient(circle,#E1306C 0%,transparent 60%)' }}
      />
      <div
        className="absolute -bottom-[30%] -left-[20%] h-[80%] w-[80%] rounded-full opacity-40 blur-[80px]"
        style={{ background: 'radial-gradient(circle,#38BDF8 0%,transparent 60%)' }}
      />
      <div className="relative z-10 flex h-full flex-col p-[60px]">
        <div className="text-[13px] font-semibold uppercase tracking-[0.4em] text-[#7DD3FC]">
          {period || 'Bi-weekly Recap'}
        </div>
        <div
          className="mt-6 font-display font-bold leading-[0.95] tracking-[-3px]"
          style={{ fontSize: 90 }}
        >
          {title}
          <br />
          <em
            className="not-italic"
            style={{
              background: 'linear-gradient(135deg,#38BDF8,#E1306C,#F59E0B)',
              WebkitBackgroundClip: 'text',
              backgroundClip: 'text',
              color: 'transparent'
            }}
          >
            Social Recap.
          </em>
        </div>
        <div className="mt-4 text-lg text-[#A5B4FC]">
          Generated by KM Socials · Command Center
        </div>
        <div className="mt-auto grid grid-cols-2 gap-4">
          {accounts.flatMap((a, i) => [
            <div
              key={`f-${i}`}
              className="rounded-2xl border border-white/[.12] bg-white/[.06] p-6 backdrop-blur-xl"
            >
              <div
                className="font-display text-[46px] font-bold leading-none tracking-[-1.5px]"
                style={{
                  background: 'linear-gradient(180deg,#fff,#A5B4FC)',
                  WebkitBackgroundClip: 'text',
                  backgroundClip: 'text',
                  color: 'transparent'
                }}
              >
                {formatNum(a.followers)}
              </div>
              <div className="mt-2 text-sm text-[#A5B4FC]">
                {a.label} · followers
              </div>
            </div>,
            <div
              key={`g-${i}`}
              className="rounded-2xl border border-white/[.12] bg-white/[.06] p-6 backdrop-blur-xl"
            >
              <div
                className="font-display text-[46px] font-bold leading-none tracking-[-1.5px]"
                style={{
                  background: 'linear-gradient(180deg,#fff,#A5B4FC)',
                  WebkitBackgroundClip: 'text',
                  backgroundClip: 'text',
                  color: 'transparent'
                }}
              >
                {a.growth >= 0 ? '+' : ''}
                {formatNum(a.growth)}
              </div>
              <div className="mt-2 text-sm text-[#A5B4FC]">
                {a.label} · growth
              </div>
            </div>
          ])}
        </div>
      </div>
    </div>
  );
}

function PlatformRecapPage({
  account,
  snapshot,
  period
}: {
  account: Account;
  snapshot: Snapshot & { posts: Post[] };
  period: string;
}) {
  const meta = PLATFORM_META[snapshot.platform];
  const accent =
    snapshot.platform === 'instagram'
      ? 'linear-gradient(135deg,#833AB4,#E1306C,#F77737)'
      : snapshot.platform === 'x'
      ? '#000000'
      : meta.color;
  return (
    <div
      className="recap-page relative overflow-hidden rounded-[14px] bg-white text-[#1a1a2e]"
      style={{ width: 864, height: 1152, boxShadow: '0 30px 80px rgba(0,0,0,.6)' }}
    >
      <div className="flex h-full flex-col p-[60px]">
        <div className="mb-8 flex items-center justify-between">
          <div className="flex items-center gap-5">
            <div
              className="flex h-[72px] w-[72px] items-center justify-center rounded-[18px] text-white shadow-[0_12px_30px_rgba(0,0,0,.18)]"
              style={{ background: accent }}
            >
              <PlatformIcon kind={snapshot.platform} className="h-8 w-8" />
            </div>
            <div>
              <div
                className="font-display font-bold leading-none tracking-[-1.4px]"
                style={{ fontSize: 38 }}
              >
                {account.tag} · {meta.name}
              </div>
              <div className="mt-1.5 text-sm text-[#6B7280]">
                {snapshot.raw && typeof snapshot.raw === 'object' && (snapshot.raw as Record<string, unknown>).handle
                  ? String((snapshot.raw as Record<string, unknown>).handle)
                  : ''}
              </div>
            </div>
          </div>
          <div className="text-right">
            <div className="text-[11px] font-bold uppercase tracking-[0.16em] text-[#9CA3AF]">
              Period
            </div>
            <div className="mt-1 font-display text-lg font-semibold">
              {period || '—'}
            </div>
          </div>
        </div>

        <div
          className="relative mb-8 flex items-center justify-between overflow-hidden rounded-[18px] p-7 text-white"
          style={{ background: accent }}
        >
          <div
            className="absolute inset-0"
            style={{
              background:
                'linear-gradient(135deg,rgba(255,255,255,.18) 0%,transparent 70%)'
            }}
          />
          <div className="relative z-10">
            <div className="text-[11px] font-semibold uppercase tracking-[0.18em] opacity-85">
              Followers gained
            </div>
            <div
              className="font-display font-bold leading-none tracking-[-2px]"
              style={{ fontSize: 64 }}
            >
              {snapshot.growth != null
                ? `${snapshot.growth >= 0 ? '+' : ''}${formatNum(snapshot.growth)}`
                : '—'}
            </div>
            <div className="mt-1.5 text-[13px] opacity-85">{account.label}</div>
          </div>
          <div className="relative z-10 text-right">
            <div
              className="font-display font-bold leading-none tracking-[-1.5px]"
              style={{ fontSize: 46 }}
            >
              {snapshot.followers != null ? formatNum(snapshot.followers) : '—'}
            </div>
            <div className="mt-1.5 text-[12px] uppercase tracking-[0.12em] opacity-85">
              Total {meta.fLabel}
            </div>
          </div>
        </div>

        <div className="mb-3 text-[11px] font-bold uppercase tracking-[0.16em] text-[#9CA3AF]">
          Top performing · {meta.name}
        </div>
        <div className="grid flex-1 grid-cols-4 gap-3.5">
          {(snapshot.posts || []).slice(0, 4).map((post, i) => (
            <PostThumb key={i} post={post} />
          ))}
          {Array.from({ length: Math.max(0, 4 - (snapshot.posts?.length || 0)) }).map(
            (_, i) => (
              <PostThumb key={`empty-${i}`} post={null} />
            )
          )}
        </div>
        <div className="absolute bottom-6 left-[60px] right-[60px] flex justify-between text-[10px] uppercase tracking-[0.12em] text-[#9CA3AF]">
          <span>{account.label}</span>
          <span>
            {meta.name} · {period}
          </span>
        </div>
      </div>
    </div>
  );
}

function PostThumb({ post }: { post: Post | null }) {
  return (
    <div className="flex flex-col overflow-hidden rounded-[14px] border border-[#E5E7EB] bg-[#F8FAFC]">
      <div className="relative aspect-[9/16] bg-gradient-to-br from-[#E5E7EB] to-[#F8FAFC]">
        {post?.thumb_blob_url || post?.media_url ? (
          /* eslint-disable-next-line @next/next/no-img-element */
          <img
            src={post.thumb_blob_url || post.media_url || ''}
            alt=""
            className="h-full w-full object-cover"
          />
        ) : (
          <div className="flex h-full w-full items-center justify-center text-3xl text-[#CBD5E1]">
            ◇
          </div>
        )}
      </div>
      <div className="bg-white p-3">
        {!!post?.views && (
          <Row label="Views" value={formatNum(post.views)} />
        )}
        {!!post?.impressions && (
          <Row label="Impr." value={formatNum(post.impressions)} />
        )}
        {!!post?.downloads && (
          <Row label="Downloads" value={formatNum(post.downloads)} />
        )}
        {!!post?.plays && (
          <Row label="Plays" value={formatNum(post.plays)} />
        )}
        {!!post?.likes && (
          <Row label="Likes" value={formatNum(post.likes)} />
        )}
        {!!post?.follows && (
          <Row label="Follows" value={formatNum(post.follows)} />
        )}
      </div>
    </div>
  );
}
function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between text-[11px]">
      <span className="text-[#6B7280]">{label}</span>
      <span className="font-display font-bold text-[#1a1a2e]">{value}</span>
    </div>
  );
}
